### ISSUE TITLE
  OSError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by ripundeep** [aalto-speech/speaker-diarization#8]
./mseg.py "/home/User/Desktop/Audio Files/51-Sleep.mp3"

Traceback (most recent call last):
  File "./mseg.py", line 280, in <module>
   main(args.infile, marks, None)
 File "./mseg.py", line 90, in main
    p = mp.Player()
  File "/home/User/.local/lib/python2.7/site-packages/mplayer/core.py", line 110, in __init__
    self.spawn()
  File "/home/User/.local/lib/python2.7/site-packages/mplayer/core.py", line 324, in spawn
    close_fds=(sys.platform != 'win32'))
 File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
  OSError: [Errno 2] No such file or directory

I have faced this error however I am unable to detect its solution. 

Please suggest that exactly how can I start with the execution of application to recognize speakers in source audio file.

**Comment by antoniomo** [comment]
Seems like you are on a Windows system, and the python `subprocess` call might not be forking on the same directory as the `unix` version: https://docs.python.org/2/library/subprocess.html#subprocess.Popen or some other issue.

I don't have a Windows platform to test and fix this and it's a Python-Windows issue so I'll close this. Your best bet is either to submit a patch, use the docker version (check the documentation), or a virtual machine with Linux.

Thanks!
